const tracks = [
  ["576, from Album 3. Sakura Dreams", ],
  ["90_s, from Album 2. Fantasy Arcade", ],
  ["A Moment Suspended, from Album 17. Electric", ],
  ["A Nomad_s Way, from Album 3. Sakura Dreams", ],
  ["A Passion For Glory, from Album 7. Gold", ],
  ["Absolutely Zero Cares, from Album 14. Neon", ],
  ["Afternoon Delight, from Album 14. Neon", ],
  ["Afternoon Drift, from Album 17. Electric", ],
  ["Aging Juniper, from Album 15. Quest", ],
  ["Ain_t No Rest For The Stars, from Album 1. High At The Planetarium", ],
  ["Akita Inu, from Album 9. Inu", ],
  ["All The Royalties, from Album 9. Inu", ],
  ["All the Right Moves, from Album 4. In 4k", ],
  ["Amber Afterglow, from Album 19. Prime", ],
  ["Amber Leaves, from Album 20. Slaps", ],
  ["Ambient Gold, from Album 7. Gold", ],
  ["Ambient Gold, from Album Single - Ambient Gold", ],
];
const track_total_time_ms = 0;
